### PR TITLE
fix: avoid fetching data/geojson multiple times

### LINKED ISSUE #305: Datasets and GeoJSONs are loaded multiple times
Fix: In `fetchMappedSets` keep track of which dataset/geojson ids are being currently loaded and prevent loading it multiple times if accidentally requested.

### PR DESCRIPTION
**Pull request by kommander**
Fixes #305

### CODE REVIEW

File: src/state/thunks/fetchMappedSet.ts [hunk 1]
```diff
@@ -52,22 +61,49 @@ export function fetchMappedSet(visualId: VisualId, mappingId: string, date: Mome
       const [data, geojson] = await Promise.all([
```
Comment (ChristophWersal) [inline src/state/thunks/fetchMappedSet.ts:61]: We could consider extracting the two async arrow functions inside the Promise.all into their separate named functions for better readability. (Either passing the common variables from the state or getting them separately directly from the state.) But the functionality looks good.

**Review by ChristophWersal — APPROVED** [review]

File: src/state/thunks/fetchMappedSet.ts (hunk 1 above)
Comment (kommander) [reply src/state/thunks/fetchMappedSet.ts:113]: Updated... check again.
